variable "cluster_count" {
  description = "The number of cluster hosts to connect to"
  type        = number
  default     = 0
}

variable "cluster_ips" {
  description = "The hostnames or addresses of the vms to connect to"
  type        = list(string)
}

variable "cluster_ssh_user" {
  description = "The name of the ssh user"
  type        = string
  default     = "centos"
}

variable "cluster_ssh_private_key" {
  description = "The ssh private key path for the ssh access key for the cluster hosts"
  type        = string
}

variable "cluster_tmp_path" {
  description = "The directory to use for executing terraform scripts"
  type        = string
  default     = "/var/tmp"
}

variable "bastion_ip" {
  description = "The hostname or address of the bastion server (if needed)"
  type        = string
  default     = null
}

variable "bastion_ssh_user" {
  description = "The name of the bastion host ssh user"
  type        = string
  default     = null
}

variable "bastion_ssh_private_key" {
  description = "The ssh private key path for the ssh access key for the bastion host"
  type        = string
  default     = null
}

variable "ssh_user_sudo_password" {
  description = "The sudo password if needed"
  type        = string
  default     = ""
}

variable "sudo_cmd" {
  description = "The commnad to call for sudo"
  type        = string
  default     = "sudo"
}

variable "cluster_script" {
  description = "A string of command to execute on the cluster hosts, normally generated by a templatefile"
  type        = string
}

variable "module_depends_on" {
  description = "List of modules or resources this module depends on."
  type        = list(any)
  default     = []
}

variable "module_depends_on_ex" {
  description = "In case we need to depend on modules of a different type to those in the module_depends_on list"
  type        = list(any)
  default     = []
}

variable "cluster_working_folder" {
  description = "The working folder for the bastion node"
  type        = string
  default     = "bastion_provision"
}
